// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            int64              `protobuf:"varint,3,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	OrderItems           []*Order_OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a6f2c4aae87bdd5c, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Order) GetOrderItems() []*Order_OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

type Order_OrderItem struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_OrderItem) Reset()         { *m = Order_OrderItem{} }
func (m *Order_OrderItem) String() string { return proto.CompactTextString(m) }
func (*Order_OrderItem) ProtoMessage()    {}
func (*Order_OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a6f2c4aae87bdd5c, []int{0, 0}
}
func (m *Order_OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderItem.Unmarshal(m, b)
}
func (m *Order_OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderItem.Marshal(b, m, deterministic)
}
func (dst *Order_OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderItem.Merge(dst, src)
}
func (m *Order_OrderItem) XXX_Size() int {
	return xxx_messageInfo_Order_OrderItem.Size(m)
}
func (m *Order_OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderItem proto.InternalMessageInfo

func (m *Order_OrderItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Order_OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order_OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Order_OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a6f2c4aae87bdd5c, []int{1}
}
func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (dst *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(dst, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*Order_OrderItem)(nil), "order.Order.OrderItem")
	proto.RegisterType((*OrderResponse)(nil), "order.OrderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	// A simple RPC
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	// A simple RPC
	CreateOrder(context.Context, *Order) (*OrderResponse, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_order_a6f2c4aae87bdd5c) }

var fileDescriptor_order_a6f2c4aae87bdd5c = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x18, 0xc4, 0xc9, 0xbf, 0xd2, 0x7c, 0x29, 0x0c, 0x56, 0x55, 0x99, 0x48, 0x48, 0x51, 0xa6, 0x4c,
	0x1d, 0xda, 0x81, 0x15, 0xa9, 0x13, 0x53, 0x90, 0x79, 0x80, 0x28, 0xc4, 0xdf, 0xe0, 0x21, 0x76,
	0xb0, 0x1d, 0x24, 0x9e, 0x9c, 0x15, 0xd9, 0x71, 0x4a, 0x97, 0xe8, 0xee, 0x22, 0xf9, 0x7e, 0x3e,
	0x43, 0xa1, 0x34, 0x47, 0x7d, 0x9c, 0xb4, 0xb2, 0x8a, 0x64, 0xde, 0xd4, 0xbf, 0x11, 0x64, 0xad,
	0x53, 0xe4, 0x11, 0x62, 0xc1, 0x69, 0x54, 0x45, 0x4d, 0xce, 0x62, 0xc1, 0xc9, 0x01, 0x36, 0xc6,
	0xf6, 0x76, 0x36, 0x34, 0xf6, 0x59, 0x70, 0xe4, 0x19, 0x60, 0xd0, 0xd8, 0x5b, 0xe4, 0x9d, 0x92,
	0x34, 0xa9, 0xa2, 0x26, 0x61, 0x79, 0x48, 0x5a, 0x49, 0x5e, 0x42, 0x4d, 0x27, 0x2c, 0x8e, 0x86,
	0xa6, 0x55, 0xd2, 0x14, 0xa7, 0xc3, 0x71, 0xa9, 0x6e, 0xff, 0xbf, 0x6f, 0x16, 0x47, 0x06, 0x6a,
	0x95, 0xa6, 0x94, 0x90, 0x5f, 0x7f, 0x10, 0x02, 0xe9, 0xa0, 0x38, 0x06, 0x1c, 0xaf, 0x5d, 0x26,
	0xfb, 0x11, 0x03, 0x8e, 0xd7, 0x0e, 0x66, 0x96, 0xc2, 0x76, 0x93, 0x16, 0x03, 0x7a, 0x98, 0x98,
	0xe5, 0x2e, 0x79, 0x77, 0x01, 0x29, 0x61, 0xfb, 0x35, 0xf7, 0xd2, 0x0a, 0xfb, 0x43, 0xd3, 0x2a,
	0x6a, 0x32, 0x76, 0xf5, 0xf5, 0x2b, 0x3c, 0xf8, 0x3e, 0x86, 0x66, 0x52, 0xd2, 0x20, 0x79, 0x82,
	0x6d, 0x20, 0x5f, 0x67, 0xb8, 0x5f, 0xf0, 0x38, 0xd9, 0x43, 0x86, 0x5a, 0x2b, 0x1d, 0xba, 0x17,
	0x73, 0xba, 0xc0, 0xce, 0x9f, 0xf0, 0x81, 0xfa, 0xdb, 0xb5, 0x9d, 0xa1, 0xb8, 0xf8, 0x1d, 0x96,
	0x41, 0x77, 0xb7, 0x97, 0x2e, 0xf7, 0xb7, 0x6e, 0xed, 0xac, 0xef, 0x3e, 0x37, 0xfe, 0x39, 0xce,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x11, 0x88, 0x35, 0x9d, 0x01, 0x00, 0x00,
}
